# MySQL connection
spring.datasource.url=jdbc:mysql://35.209.160.138:3306/dbdshkv8vs4hkb?useSSL=false&serverTimezone=UTC
spring.datasource.username=ujprjc3lsb8mv
spring.datasource.password=tlwm0yoppngp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never

# MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.sql.init.platform=mysql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

# Internationalization
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h

# Set to dev locally, and prod on a cloud server
spring.profiles.active=dev

# Disable Whitelabel error page so custom error templates are used
#server.error.whitelabel.enabled=false

azure.communication.connection-string=${AZURE_COMMUNICATION_CONNECTION_STRING:}
azure.communication.sender-email=${AZURE_COMMUNICATION_SENDER_EMAIL:}
app.base-url=http://localhost:8080

