# Display detailed error information on localhost
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

# Azure Communication Services (email)
azure.communication.connection-string=YOUR_AZURE_CONNECTION_STRING_HERE
azure.communication.sender-email=DoNotReply@9f6aba2c-dd25-4d15-9445-0bd717cb6122.azurecomm.net
