-- PostgreSQL schema for weFixCar
-- Converted from MySQL: ENGINE/CHARSET removed, AUTO_INCREMENT→SERIAL,
-- DATETIME→TIMESTAMP, TINYINT→BOOLEAN, ENUM→VARCHAR+CHECK,
-- inline INDEX definitions moved to separate CREATE INDEX statements,
-- ON UPDATE CURRENT_TIMESTAMP removed (not supported in PostgreSQL).

-- ─── Petclinic base tables ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX IF NOT EXISTS idx_vets_last_name ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX IF NOT EXISTS idx_specialties_name ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX IF NOT EXISTS idx_types_name ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX IF NOT EXISTS idx_owners_last_name ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX IF NOT EXISTS idx_pets_name ON pets (name);
CREATE INDEX IF NOT EXISTS idx_pets_owner_id ON pets (owner_id);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX IF NOT EXISTS idx_visits_pet_id ON visits (pet_id);

-- ─── Users, roles, permissions ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id                     SERIAL PRIMARY KEY,
  first_name             VARCHAR(50),
  last_name              VARCHAR(50),
  nickname               VARCHAR(50),
  nickname_is_flagged    BOOLEAN      DEFAULT FALSE,
  email                  VARCHAR(255) NOT NULL UNIQUE,
  public_email           BOOLEAN      DEFAULT FALSE,
  phone                  VARCHAR(255),
  preferred_language     VARCHAR(50),
  public_phone           BOOLEAN      DEFAULT FALSE,
  password_hash          VARCHAR(255),
  is_active              BOOLEAN      DEFAULT TRUE,
  is_approved            BOOLEAN      DEFAULT FALSE,
  created_at             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted_at             TIMESTAMP,
  reset_token            VARCHAR(255),
  reset_token_expires_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_users_name ON users (last_name, first_name);

CREATE TABLE IF NOT EXISTS roles (
  id          SERIAL PRIMARY KEY,
  name        VARCHAR(50)  NOT NULL UNIQUE,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS permissions (
  id          SERIAL PRIMARY KEY,
  name        VARCHAR(100) NOT NULL UNIQUE,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

-- Name matches @JoinTable(name = "role_permissions") in Role.java
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id       INTEGER NOT NULL,
  permission_id INTEGER NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

-- ─── Schools & locations ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS schools (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  domain     VARCHAR(255) NOT NULL UNIQUE,
  status_id  VARCHAR(20)  DEFAULT 'ACTIVE' CHECK (status_id IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
  created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS locations (
  id                 SERIAL PRIMARY KEY,
  school_id          INTEGER      NOT NULL,
  parent_location_id INTEGER,
  name               VARCHAR(255) NOT NULL,
  description        TEXT,
  address            VARCHAR(255),
  latitude           DECIMAL(8, 4),
  longitude          DECIMAL(8, 4),
  status_id          VARCHAR(20)  DEFAULT 'ACTIVE' CHECK (status_id IN ('DRAFT', 'ACTIVE', 'CLOSED', 'COMING_SOON')),
  created_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted_at         TIMESTAMP,
  CONSTRAINT fk_locations_school FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE,
  CONSTRAINT fk_locations_parent FOREIGN KEY (parent_location_id) REFERENCES locations (id) ON DELETE SET NULL,
  UNIQUE (school_id, name)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id            SERIAL PRIMARY KEY,
  name          VARCHAR(255) NOT NULL UNIQUE,
  description   TEXT         NOT NULL,
  monthly_price INTEGER      NOT NULL,
  annual_price  INTEGER      NOT NULL,
  created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted_at    TIMESTAMP
);

-- ─── Car shop tables ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS customer (
  customer_id   SERIAL PRIMARY KEY,
  user_id       INTEGER,
  customer_name VARCHAR(255) NOT NULL,
  phone         VARCHAR(20)  NOT NULL,
  email         VARCHAR(255),
  status        VARCHAR(20)  DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
  created_date  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_date  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted_at    TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS vehicle (
  vin             VARCHAR(17)  NOT NULL PRIMARY KEY,
  customer_id     INTEGER,
  make            VARCHAR(255) NOT NULL,
  model           VARCHAR(255) NOT NULL,
  model_year      INTEGER      NOT NULL,
  color           VARCHAR(100),
  license_plate   VARCHAR(50),
  current_mileage INTEGER,
  status          VARCHAR(20)  DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'IN_SERVICE', 'RETIRED')),
  created_date    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted_at      TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS service_appointment (
  appointment_id   SERIAL PRIMARY KEY,
  customer_id      INTEGER       NOT NULL,
  vin              VARCHAR(17)   NOT NULL,
  appointment_date TIMESTAMP     NOT NULL,
  description      VARCHAR(1024),
  status           VARCHAR(20)   NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'In_Progress', 'Completed', 'Cancelled', 'No_Show')),
  notes            TEXT,
  created_date     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
  FOREIGN KEY (vin) REFERENCES vehicle (vin) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_appointment_customer_id ON service_appointment (customer_id);
CREATE INDEX IF NOT EXISTS idx_appointment_vin ON service_appointment (vin);
CREATE INDEX IF NOT EXISTS idx_appointment_date ON service_appointment (appointment_date);
CREATE INDEX IF NOT EXISTS idx_appointment_status ON service_appointment (status);

CREATE TABLE IF NOT EXISTS employee (
  employee_id  SERIAL PRIMARY KEY,
  first_name   VARCHAR(50)  NOT NULL,
  last_name    VARCHAR(50)  NOT NULL,
  role         VARCHAR(20)  NOT NULL CHECK (role IN ('Technician', 'Service_Advisor', 'Manager', 'Receptionist')),
  email        VARCHAR(255),
  phone        VARCHAR(20),
  hired_date   DATE,
  status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_date TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at   TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_employee_last_name ON employee (last_name);

CREATE TABLE IF NOT EXISTS service_catalog (
  service_catalog_id  SERIAL PRIMARY KEY,
  name                VARCHAR(100)  NOT NULL,
  description         VARCHAR(500),
  category            VARCHAR(30)   NOT NULL DEFAULT 'OTHER' CHECK (category IN ('GENERAL_SERVICE', 'OIL_CHANGE', 'TIRE_SERVICE', 'BRAKE_SERVICE', 'BATTERY_SERVICE', 'INSPECTION', 'DIAGNOSTIC', 'ELECTRICAL', 'TRANSMISSION', 'AC_COOLING', 'FILTERS_WIPERS', 'ALIGNMENT', 'OTHER')),
  default_labor_hours DECIMAL(5, 2),
  default_price       DECIMAL(10, 2),
  status              VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_date        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at          TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_catalog_category ON service_catalog (category);
CREATE INDEX IF NOT EXISTS idx_catalog_status ON service_catalog (status);

CREATE TABLE IF NOT EXISTS service_line (
  service_line_id      SERIAL PRIMARY KEY,
  appointment_id       INTEGER        NOT NULL,
  service_catalog_id   INTEGER,
  vin                  VARCHAR(17)    NOT NULL,
  service_date         TIMESTAMP      NOT NULL,
  service_description  VARCHAR(1024)  NOT NULL,
  labor_hours          DECIMAL(5, 2),
  labor_rate           DECIMAL(8, 2),
  labor_cost           DECIMAL(10, 2),
  parts_cost           DECIMAL(10, 2),
  total_cost           DECIMAL(10, 2) NOT NULL DEFAULT 0,
  notes                VARCHAR(1024),
  assigned_to          INTEGER,
  status               VARCHAR(20)    NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'In_Progress', 'Completed', 'Cancelled')),
  created_date         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (appointment_id) REFERENCES service_appointment (appointment_id) ON DELETE CASCADE,
  FOREIGN KEY (service_catalog_id) REFERENCES service_catalog (service_catalog_id) ON DELETE SET NULL,
  FOREIGN KEY (vin) REFERENCES vehicle (vin) ON DELETE CASCADE,
  FOREIGN KEY (assigned_to) REFERENCES employee (employee_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_service_line_appointment_id ON service_line (appointment_id);
CREATE INDEX IF NOT EXISTS idx_service_line_assigned_to ON service_line (assigned_to);
CREATE INDEX IF NOT EXISTS idx_service_line_status ON service_line (status);

CREATE TABLE IF NOT EXISTS service_line_item (
  service_line_item_id SERIAL PRIMARY KEY,
  service_line_id      INTEGER        NOT NULL,
  service_catalog_id   INTEGER,
  item_type            VARCHAR(10)    NOT NULL CHECK (item_type IN ('Service', 'Part', 'Labor')),
  description          VARCHAR(500)   NOT NULL,
  quantity             DECIMAL(8, 2)  NOT NULL DEFAULT 1,
  unit_price           DECIMAL(10, 2) NOT NULL,
  total_price          DECIMAL(10, 2) NOT NULL,
  notes                VARCHAR(500),
  created_date         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (service_line_id) REFERENCES service_line (service_line_id) ON DELETE CASCADE,
  FOREIGN KEY (service_catalog_id) REFERENCES service_catalog (service_catalog_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_sli_service_line_id ON service_line_item (service_line_id);
CREATE INDEX IF NOT EXISTS idx_sli_catalog_id ON service_line_item (service_catalog_id);

CREATE TABLE IF NOT EXISTS invoice (
  invoice_id     SERIAL PRIMARY KEY,
  invoice_number VARCHAR(50)    NOT NULL UNIQUE,
  appointment_id INTEGER        NOT NULL,
  customer_id    INTEGER        NOT NULL,
  vin            VARCHAR(17)    NOT NULL,
  invoice_date   TIMESTAMP      NOT NULL,
  due_date       TIMESTAMP,
  subtotal       DECIMAL(10, 2) NOT NULL DEFAULT 0,
  tax_rate       DECIMAL(5, 4)  NOT NULL DEFAULT 0.0700,
  tax_amount     DECIMAL(10, 2) NOT NULL DEFAULT 0,
  total_amount   DECIMAL(10, 2) NOT NULL DEFAULT 0,
  amount_paid    DECIMAL(10, 2) NOT NULL DEFAULT 0,
  status         VARCHAR(10)    NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Sent', 'Paid', 'Partial', 'Void')),
  notes          TEXT,
  created_by     INTEGER        NOT NULL,
  created_date   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (appointment_id) REFERENCES service_appointment (appointment_id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
  FOREIGN KEY (vin) REFERENCES vehicle (vin) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_invoice_appointment_id ON invoice (appointment_id);
CREATE INDEX IF NOT EXISTS idx_invoice_customer_id ON invoice (customer_id);
CREATE INDEX IF NOT EXISTS idx_invoice_status ON invoice (status);
CREATE INDEX IF NOT EXISTS idx_invoice_date ON invoice (invoice_date);

CREATE TABLE IF NOT EXISTS recipes (
  id                 BIGSERIAL PRIMARY KEY,
  recipe_ingredients VARCHAR(255),
  instructions       VARCHAR(255) NOT NULL,
  type               VARCHAR(50),
  category           VARCHAR(50),
  dietary_preference VARCHAR(50),
  internal_notes     VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS payment (
  payment_id     SERIAL PRIMARY KEY,
  invoice_id     INTEGER        NOT NULL,
  payment_date   TIMESTAMP      NOT NULL,
  payment_method VARCHAR(20)    NOT NULL CHECK (payment_method IN ('Cash', 'Credit_Card', 'Debit_Card', 'Check', 'Bank_Transfer')),
  amount         DECIMAL(10, 2) NOT NULL,
  transaction_id VARCHAR(100),
  received_by    INTEGER        NOT NULL,
  notes          VARCHAR(500),
  created_date   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invoice_id) REFERENCES invoice (invoice_id) ON DELETE CASCADE,
  FOREIGN KEY (received_by) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT chk_payment_amount CHECK (amount > 0)
);
CREATE INDEX IF NOT EXISTS idx_payment_invoice_id ON payment (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payment_date ON payment (payment_date);
CREATE INDEX IF NOT EXISTS idx_payment_received_by ON payment (received_by);

CREATE TABLE IF NOT EXISTS estimate (
  estimate_id              SERIAL PRIMARY KEY,
  estimate_number          VARCHAR(50)    NOT NULL UNIQUE,
  customer_id              INTEGER        NOT NULL,
  vin                      VARCHAR(17)    NOT NULL,
  estimate_date            TIMESTAMP      NOT NULL,
  valid_until              TIMESTAMP,
  description              VARCHAR(1024),
  labor_cost               DECIMAL(10, 2) NOT NULL,
  parts_cost               DECIMAL(10, 2) NOT NULL,
  tax_amount               DECIMAL(10, 2) NOT NULL,
  total_estimate           DECIMAL(10, 2) NOT NULL,
  status                   VARCHAR(10)    NOT NULL CHECK (status IN ('Draft', 'Sent', 'Approved', 'Rejected', 'Expired')),
  approved_date            TIMESTAMP,
  converted_to_appointment BOOLEAN        NOT NULL DEFAULT FALSE,
  appointment_id           INTEGER,
  prepared_by              INTEGER        NOT NULL,
  created_date             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
  FOREIGN KEY (vin) REFERENCES vehicle (vin) ON DELETE CASCADE,
  FOREIGN KEY (appointment_id) REFERENCES service_appointment (appointment_id) ON DELETE SET NULL,
  FOREIGN KEY (prepared_by) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_estimate_customer_id ON estimate (customer_id);
CREATE INDEX IF NOT EXISTS idx_estimate_vin ON estimate (vin);
CREATE INDEX IF NOT EXISTS idx_estimate_status ON estimate (status);
CREATE INDEX IF NOT EXISTS idx_estimate_date ON estimate (estimate_date);

CREATE TABLE IF NOT EXISTS estimate_line_item (
  estimate_line_item_id SERIAL PRIMARY KEY,
  estimate_id           INTEGER        NOT NULL,
  item_type             VARCHAR(10)    NOT NULL CHECK (item_type IN ('Service', 'Part', 'Labor')),
  description           VARCHAR(500)   NOT NULL,
  quantity              DECIMAL(8, 2)  NOT NULL DEFAULT 1,
  unit_price            DECIMAL(10, 2) NOT NULL,
  total_price           DECIMAL(10, 2) NOT NULL,
  notes                 VARCHAR(500),
  FOREIGN KEY (estimate_id) REFERENCES estimate (estimate_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_estimate_line_item_estimate_id ON estimate_line_item (estimate_id);

CREATE TABLE IF NOT EXISTS customer_communication (
  communication_id   SERIAL PRIMARY KEY,
  customer_id        INTEGER     NOT NULL,
  appointment_id     INTEGER,
  communication_type VARCHAR(20) NOT NULL CHECK (communication_type IN ('Phone_Call', 'Email', 'SMS', 'In_Person', 'Other')),
  direction          VARCHAR(10) NOT NULL CHECK (direction IN ('Inbound', 'Outbound')),
  subject            VARCHAR(256),
  notes              TEXT,
  contacted_by       INTEGER,
  communication_date TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  follow_up_required BOOLEAN     NOT NULL DEFAULT FALSE,
  follow_up_date     TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
  FOREIGN KEY (appointment_id) REFERENCES service_appointment (appointment_id) ON DELETE SET NULL,
  FOREIGN KEY (contacted_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_communication_customer_id ON customer_communication (customer_id);
CREATE INDEX IF NOT EXISTS idx_communication_appointment_id ON customer_communication (appointment_id);
CREATE INDEX IF NOT EXISTS idx_communication_date ON customer_communication (communication_date);
CREATE INDEX IF NOT EXISTS idx_communication_follow_up ON customer_communication (follow_up_required, follow_up_date);

CREATE TABLE IF NOT EXISTS vehicle_service_history (
  service_history_id SERIAL PRIMARY KEY,
  vin                VARCHAR(17)    NOT NULL,
  appointment_id     INTEGER        NOT NULL,
  service_date       TIMESTAMP      NOT NULL,
  mileage            INTEGER,
  service_summary    VARCHAR(1024)  NOT NULL,
  total_cost         DECIMAL(10, 2) NOT NULL,
  performed_by       INTEGER,
  created_date       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vin) REFERENCES vehicle (vin) ON DELETE CASCADE,
  FOREIGN KEY (appointment_id) REFERENCES service_appointment (appointment_id) ON DELETE CASCADE,
  FOREIGN KEY (performed_by) REFERENCES employee (employee_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_service_history_vin ON vehicle_service_history (vin);
CREATE INDEX IF NOT EXISTS idx_service_history_appointment_id ON vehicle_service_history (appointment_id);
CREATE INDEX IF NOT EXISTS idx_service_history_date ON vehicle_service_history (service_date);

CREATE TABLE IF NOT EXISTS customer_invitations (
  id               SERIAL PRIMARY KEY,
  customer_id      INTEGER      NOT NULL,
  email            VARCHAR(255) NOT NULL,
  invitation_token VARCHAR(255) NOT NULL UNIQUE,
  invited_by       INTEGER,
  invited_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  expires_at       TIMESTAMP    NOT NULL,
  is_used          BOOLEAN      DEFAULT FALSE,
  used_at          TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
  FOREIGN KEY (invited_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_invitation_token ON customer_invitations (invitation_token);
CREATE INDEX IF NOT EXISTS idx_invitation_customer ON customer_invitations (customer_id);

CREATE TABLE IF NOT EXISTS appointment_reminder (
  reminder_id    SERIAL PRIMARY KEY,
  appointment_id INTEGER     NOT NULL,
  reminder_type  VARCHAR(15) NOT NULL CHECK (reminder_type IN ('Email', 'SMS', 'Phone_Call')),
  scheduled_date TIMESTAMP   NOT NULL,
  sent_date      TIMESTAMP,
  status         VARCHAR(15) NOT NULL CHECK (status IN ('Scheduled', 'Sent', 'Failed', 'Cancelled')),
  message        TEXT,
  created_date   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (appointment_id) REFERENCES service_appointment (appointment_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_reminder_appointment_id ON appointment_reminder (appointment_id);
CREATE INDEX IF NOT EXISTS idx_reminder_status ON appointment_reminder (status);
CREATE INDEX IF NOT EXISTS idx_reminder_scheduled_date ON appointment_reminder (scheduled_date);
